#!/bin/bash
set -e;


if [ -n "${POSTGRES_MM_USER:-}" ] && [ -n "${POSTGRES_MM_PASSWORD:-}" ]; then
	psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
		CREATE DATABASE ${POSTGRES_MM_DB};
		CREATE USER ${POSTGRES_MM_USER} WITH PASSWORD '${POSTGRES_MM_PASSWORD}';
		GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_MM_DB} TO ${POSTGRES_MM_USER};
	EOSQL
else
	echo "SETUP INFO: No Mattermost SQL Environment variables given!"
fi

if [ -n "${POSTGRES_N8N_USER:-}" ] && [ -n "${POSTGRES_N8N_PASSWORD:-}" ]; then
	psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
		CREATE DATABASE ${POSTGRES_N8N_DB};
		CREATE USER ${POSTGRES_N8N_USER} WITH PASSWORD '${POSTGRES_N8N_PASSWORD}';
		GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_N8N_DB} TO ${POSTGRES_N8N_USER};
	EOSQL
else
	echo "SETUP INFO: No n8n SQL Environment variables given!"
fi

if [ -n "${POSTGRES_ODOO_USER:-}" ] && [ -n "${POSTGRES_ODOO_PASSWORD:-}" ]; then
	psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
		CREATE DATABASE ${POSTGRES_ODOO_DB};
		CREATE USER ${POSTGRES_ODOO_USER} WITH PASSWORD '${POSTGRES_ODOO_PASSWORD}';
		GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_ODOO_DB} TO ${POSTGRES_ODOO_USER};
	EOSQL
else
	echo "SETUP INFO: No Odoo SQL Environment variables given!"
fi
		# ALTER DATABASE ${POSTGRES_ODOO_DB} OWNER	TO ${POSTGRES_ODOO_USER};
